# Generated by Django 5.2 on 2026-03-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="assign_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
