# Generated by Django 5.2 on 2026-03-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
