# Generated by Django 5.2 on 2026-03-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_managers_delete_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolment',
            field=models.ManyToManyField(blank=True, to='app.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(blank=True, to='app.course'),
        ),
    ]
